### ISSUE TITLE
1.13.3 BC break

### ISSUE THREAD

**Issue by oojacoboo** [doctrine/annotations#443] opened 2022-07-07 06:53 UTC
Please see this PR: https://github.com/thecodingmachine/graphqlite/pull/496#issuecomment-1177161111

You can clone this repo, change the `doctrine/annotations` version in `composer.json`, run `composer update`, and then `phpunit` to see the a reproducible error.

**Comment by stof** [comment] 2022-07-07 08:22
doctrine/annotations now catches exceptions happening during the instantiation of annotations, wrapping them into an exception that explains that this was happening during the instantiation of an annotation (and which class was annotated).

It looks like your testsuite is expecting to get the original exception without wrapper.

**Comment by andrew-demb** [comment] 2022-07-07 08:38
I can help with reproducer to make issue more clear:

```php
<?php

namespace Issue;

use PHPUnit\Framework\TestCase;
use ReflectionClass;

class TestIssue extends TestCase
{
    public function testIssue(): void
    {
        $reader = new \Doctrine\Common\Annotations\AnnotationReader();

        $this->expectException(\LogicException::class);

        $reader->getClassAnnotation(
            new ReflectionClass(
                new
                /** @\Issue\CustomAnnotation */
                class {
                }
            ),
            CustomAnnotation::class
        );
    }
}

/**
 * @Annotation
 * @Target({"CLASS"})
 */
class CustomAnnotation
{
    public function __construct()
    {
        throw new \LogicException('just an example');
    }
}
```

**Comment by stof** [comment] 2022-07-07 08:47
Wrapping exceptions thrown during instantiation was done on purpose, to make it easier to understand where the exception is happening (pointing to the class and property where the annotation is used).
The original exception is still preserved as the previous exception of the chain.

**Comment by greg0ire** [comment] 2022-07-07 10:57
> You can clone this repo, change the doctrine/annotations version in composer.json, run composer update, and then phpunit to see the a reproducible error.

Digging through the "actions" tab of that repo, the pipeline with the exception can still be found: https://github.com/thecodingmachine/graphqlite/runs/7228177041?check_suite_focus=true#step:8:24

**Comment by oojacoboo** [comment] 2022-07-07 11:00
@greg0ire yes.  You can see under the composer deps action that it's `Locking doctrine/annotations (1.13.3)`.  We'll have to patch the implementation as @stof mentioned to support 1.13.3.  Or just leave it locked possibly, until docblock annotations are removed.

**Comment by greg0ire** [comment] 2022-07-07 11:33
From a look at the  test, it looks to me that you've been implementing the feature that was missing on `doctrine/annotation` itself: ensuring that you get information about the annotation and the class it was declared on: https://github.com/thecodingmachine/graphqlite/blob/470572d9e5ba3e89c24800e194456186b24565cd/tests/AnnotationReaderTest.php#L117-L124

`ClassNotFoundException` does not seem to be caught anywhere in the codebase: https://github.com/thecodingmachine/graphqlite/search?q=ClassNotFoundException

I'd suggest asserting that the exception message contains the name of the annotation, and that it contains the class the annotation was declared on, and nothing more.

Although throwing another exception type than the underlying one is a change in behavior, that behavior was never documented in the first place, I don't think we should consider it part of our BC promise. IMO we should close this.

**Comment by malarzm** [comment] 2022-07-07 13:07
Agreed :+1:

**Closed as completed by malarzm** 2022-07-07 13:07 UTC
