### ISSUE TITLE
Regex spaces

### ISSUE THREAD

**Issue by aaronahearne** [doctrine/annotations#94] opened 2016-09-13 15:41 UTC
Spaces are not parsed correctly within requirements regex and must be replaced with \s. For example:

**Does not work**

`* @QueryParam(name="departureTime", requirements="\d{4}-[01]\d-[0-3]\d [0-2]\d:[0-5]\d:[0-5]\d", strict=true, nullable=false)`

**Works**

`* @QueryParam(name="departureTime", requirements="\d{4}-[01]\d-[0-3]\d\s[0-2]\d:[0-5]\d:[0-5]\d", strict=true, nullable=false)`

This may be a FOSRestBundle issue or an annotations issue, Im unsure.

**Comment by mikeSimonson** [comment] 2016-10-26 12:30
@aaronahearne I couldn't reproduce the issue.
It might have been fixed by the last release (1.3).

In case I added an explicit test about it in #101

Thanks

**Closed by mikeSimonson** 2016-10-26 12:30 UTC
