### ISSUE TITLE
Missing annotations with the latest composer version

### ISSUE THREAD

**Issue by CracyCrazz** [doctrine/annotations#115] opened 2017-01-04 13:35 UTC
Hey guys,

I have already posted this issue in the doctrine2 Repository as well as the composer repository itself see:

https://github.com/doctrine/doctrine2/issues/6214
https://github.com/composer/composer/issues/6038

Just a short briefing: Since the latest update to the composer version 1.3 some annotations can't be found in our Symfony applications for example the PrePersist Annotation in our entity.

This only happens if we prefix the use statement with a "\" like: 

`use \Doctrine\ORM\Mapping as ORM;`

Once we remove that prefix everything works out fine.

Before composer version 1.3 it worked out fine as composer itself replaced the first character if it was an backslash as an workaround for an old PHP 5.3 issue.

According to Seladek, one of the composer members, this issue is related to the way the parser handles the namespace as it is and not replaces the prefixed slash.

I was about to start a PR for this but then I found a comment here:

https://github.com/doctrine/annotations/blob/b544ea1f2f2e1af294dbd516d4ddecd3db3d7e33/lib/Doctrine/Common/Annotations/DocParser.php#L689

And was wondering if all of this is intended or not?

Would appreciate any answer.

**Comment by Ocramius** [comment] 2017-01-04 13:38
@CracyCrazz this needs a failing test case: can't really do anything with the description provided so far.

**Comment by stof** [comment] 2017-01-04 14:38
@CracyCrazz Can you should us how your usage of ``AnnotationRegistry`` looks like (there should be at least a place using it in your project, outside the doctrine/annotations code itself) ?

**Comment by rommsen** [comment] 2017-01-06 15:41
I cant provide a failing test case because I really dont understand what is happening here but I spent the last 8 hours trying to find a reason why suddenly our JmsJobBundle was not working anymore.

We got many `PHP Warning:  Invalid argument supplied for foreach() in vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php on line 125` warnings because `$this->getPropertyAnnotations($property)` returns null in some occasions

Furthermore we had this error: ` [Doctrine\ORM\Query\QueryException]                                                                                                                          
  [Semantical Error] line 0, col 118 near 'queue NOT IN(:excludedQueues)': Error: Class JMS\JobQueueBundle\Entity\Job has no field or association named queue`
but the annotation is clearly there: https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Entity/Job.php#L98

This problem occurs only with composer 1.3.0 AND Symfony 3.2.x. It vanishes with composer 1.2.4 OR Symfony 3.1.x (at least for us).

Is there any other info I could provide to shed some light on this?

**Comment by rommsen** [comment] 2017-01-09 14:27
Ok, scratch that comment about composer 1.2.4. It is related to `--optimize-autoloader` when doing composer install. It breaks when the autoloader is optimized and dont break when I only do `composer install`. Still only in Symfony 3.2 and not in 3.1. @fancyweb said in symfony slack that there is a [PR](https://github.com/symfony/symfony/pull/20959) that has something to do with cached annotations but I dont see how this PR could fix this specific problem. Maybe I am wrong

**Comment by fancyweb** [comment] 2017-01-09 14:33
@rommsen Since you don't end up with an `AnnotationException`, the PR won't fix anything for you. Your problem is another one but it might be related, since the circumstances are similar.

**Comment by rommsen** [comment] 2017-01-09 15:55
The problem is that the JMSJobQueueBundle uses a class constant in its annotation: https://github.com/schmittjoh/JMSJobQueueBundle/blob/master/Entity/Job.php#L98 and the CachedReader is not able to find the class and throws an `ReflectionException` ("Class Job does not exist") . When I change the class constant in the annotation to a FQCN the exception is gone. Is this a bug in the bundle or in the CachedReader because it needs a FCQN to work properly?

This was not a problem before Symfony 3.2 because now there is a AnnotationCacheWarmer which can not cache the annotation in question

**Comment by cdaguerre** [comment] 2017-01-10 16:23
@stof Hi, I'm having the same problem using the `AnnotationRegistry` like in [symfony standard autoload](https://github.com/symfony/symfony-standard/blob/master/app/autoload.php)

**Comment by Seldaek** [comment] 2017-02-08 07:35
The bug as I understand it (in case it helps someone get it fixed) is that the `use` statements parsing in this lib does not trim leading backslashes, even though it should, before sending the classname to the autoloader to check if it exists. As this lib still uses the autoloader manually instead of doing `class_exists()`, php doesn't have a chance to trim the leading backslash and therefore it fails in the composer autoloader.

**Closed** 2017-02-09 23:37 UTC
Labels: bug, missing tests
