### ISSUE TITLE
@phpcsSuppress annotation is not being ignored.

### ISSUE THREAD

**Issue by phpeek** [doctrine/annotations#277] opened 2019-09-09 08:46 UTC
I'm using `v1.7.0` of this library and seeing this issue.

`@phpcsSuppress` is not being ignored.

I see that PR that's ignoring it has been merged long time ago - https://github.com/doctrine/annotations/pull/229

**Comment by Ocramius** [comment] 2019-09-09 08:48
Can you write a test case reproducing this, please?

**Comment by stof** [comment] 2019-09-09 09:16
the PR was merged in master, not in 1.7

**Comment by phpeek** [comment] 2019-09-09 09:18
@stof @Ocramius Yes, You're right it was targeted at `master`.

I forgot to mention that release notes for 1.7.0 mentions adding this annotation to ignore list.

https://github.com/doctrine/annotations/releases/tag/v1.7.0

I'll try to issue PR with repro test case later.

**Comment by phpeek** [comment] 2019-09-09 09:25
I've added PR that should fix this targeted at `1.7` branch.

https://github.com/doctrine/annotations/pull/278

Without a test-case for now. Will do that later today.

**Comment by alcaeus** [comment] 2019-09-09 10:30
As mentioned in the PR, I'll have to double-check why the PR was added to the 1.7 milestone but is not contained in the release. Since the code is already in master, there's no need for an additional PR.

**Comment by phpeek** [comment] 2019-09-16 22:01
@alcaeus Do we have any info on this issue ? My PR has been canceled since `1.7` is locked for any new features. Since then, I'm using my fork to overcome this and that's totally fine. :) Is there any chance for `1.7.1` release with this fix ?

**Comment by alcaeus** [comment] 2019-09-17 18:34
Sorry for the delay, and even more sorry for the mishap. It looks like there were three pull requests that were merged to master after we split off a 1.7 branch and were never backported to 1.7, but flagged for the 1.7 milestone. This affects #229, #230, and #235. I'll backport these to the 1.8 branch and tag a new release next week. I might get to that before then, but can't make any guarantees.

If you'd like to backport these yourself, feel free to give it a shot and create separate pull requests to the 1.8 branch for these. I've just pushed a new 1.8 branch, so feel free to add it there.

To avoid this in the future, I've also set the new default branch of the repository to 1.8, as the 2.0 version is still in heavy development, so new features should first target the 1.x release line until we've got a better plan of action for 2.0.

**Comment by phpeek** [comment] 2019-09-19 11:22
@alcaeus Thank You !

I'll issue a backport PR to `1.8` later today.

**Comment by alcaeus** [comment] 2019-10-01 18:28
Thanks for your work @phpeek! 1.8.0 with the missing features will be released soon. I'll make sure to merge up to master before releasing, so give me a few moments to make sure we're not leaving anything behind or breaking anything else :)

**Closed by alcaeus** 2019-10-01 18:28 UTC
Labels: bug
