### ISSUE TITLE
Annotation parameters

### ISSUE THREAD

**Issue by sgehrig** [doctrine/annotations#67] opened 2015-12-17 09:18 UTC
Don't know if I do not understand correctly how annotation parameters work, but given the following annotation definition:

``` php
/**
 * Class Parameter
 *
 * @Annotation
 * @Target("METHOD")
 */
class Parameter
{
    /**
     * @var string
     */
    public $name;

    /**
     * @var array<Symfony\Component\Validator\Constraint>
     */
    public $constraints = array();

    /**
     * @var string
     */
    public $validationGroup;

    /**
     * @param array $data
     */
    public function __construct(array $data)
    {
        // constructor logic
    }
}
```

Why doesn't the following work:

``` php
@Direct\Parameter("a", { @Assert\NotNull() }, "myGroup")
```

I'm getting a `Expected Value, got 'myGroup' at position 70 in method...` exception.

This however works:

``` php
@Direct\Parameter("a", { @Assert\NotNull() }, validationGroup="myGroup")
```

as does this:

``` php
@Direct\Parameter(name="a", constraints={ @Assert\NotNull() }, validationGroup="myGroup")
```

and this:

``` php
@Direct\Parameter("a", { @Assert\NotNull() })
```

**Comment by sgehrig** [comment] 2015-12-17 09:52
Strangely it works if I change the `$validationGroup` to accept (to require) an array of strings.

```php
@Direct\Parameter("a", { @Assert\NotNull() }, {"myGroup"})
```

It seems as if there is a reason for that parser behavior, but perhaps someone could point me into the right direction.

**Comment by stof** [comment] 2015-12-17 09:54
Well, if your annotation class contains a constructor, the parser will call the constructor and let it do what it want with the data instead of setting public properties. This means that the issue cannot be solved without seeing what code you have inside your constructor

**Comment by sgehrig** [comment] 2015-12-17 09:58
@stof The problem is not within the constructor. The constructor is ever reached because the annotation parser (`Doctrine\Common\Annotations\DocParser`) fails in line `861`. 

```php
if ( ! is_object($value) && ! is_array($value)) {
    $this->syntaxError('Value', $token);
}
```

`$value` in this case is the simple string `myGroup`.

**Comment by stof** [comment] 2015-12-17 10:07
The issue is that ``@Direct\Parameter("a", { @Assert\NotNull() }, "myGroup")`` contains 3 unnamed settings, and the annotations allow only one (which will be stored in the ``value`` setting)

**Comment by sgehrig** [comment] 2015-12-17 10:13
But why does it work with two unnamed parameters? And with 3 if third one is an array for example ([see here](https://github.com/doctrine/annotations/issues/67#issuecomment-165403009)) ?

**Comment by stof** [comment] 2015-12-17 10:18
I would say that this is a bug in the parser (if you examine the data, do you receive all of them ?)

**Comment by sgehrig** [comment] 2015-12-17 11:34
Yes, everything looks fine until it hits this `if ( ! is_object($value) && ! is_array($value)) {` test. I don't know why this is in there but actually that stops you from using simple non-named parameters at any other position than the first one. In line `848` `$this->Value()` is called for the first argument token and the return value is not validated. After that the test is applied to all other argument tokens.

**Comment by stof** [comment] 2015-12-17 11:55
@sgehrig but how does the ``$data`` look like in the constructor when using your working cases ?

**Comment by sgehrig** [comment] 2015-12-17 11:59
When running the parser against `@Direct\Parameter("a", { @Assert\NotNull() }, {"myGroup"})`, I'm receiving the following in the constructor:
```php
array(
    'value' =>
        array(
            0 => 'a',
            1 =>
                array(
                    0 =>
                        Symfony\Component\Validator\Constraints\NotNull::__set_state(array(
                            'message' => 'This value should not be null.',
                            'payload' => null,
                        )),
                ),
            2 =>
                array(
                    0 => 'myGroup',
                ),
        ),
)
```
Which seems to be OK for me.

**Comment by sgehrig** [comment] 2015-12-21 09:51
@stof Any news on this one? Could you verify why the code works just like it works? Is this validation required or could it simply be dropped?

**Comment by sgehrig** [comment] 2016-03-14 14:15
@stof ping

**Comment by sgehrig** [comment] 2017-02-06 20:22
Sorry for being annoying here ;-) 
Is there any interest in this issue? If not, please close it.

**Comment by Ocramius** [comment] 2017-02-07 09:10
Requires test case with expected output. Parsing issues can be fixed after the scenario and the expected values are settled.

**Comment by sgehrig** [comment] 2017-02-07 09:37
These would be the test cases to add to the `DocParserTest`:

```php
    public function testIssue67_1()
    {
        $parser = $this->createTestParser();

        // Nested arrays with nested annotations
        $result = $parser->parse('@Name("a", { "b" }, "c")');
        $annot = $result[0];

        self::assertInstanceOf(Name::class, $annot);
        self::assertNull($annot->value);
        self::assertCount(3, $annot->foo);
        self::assertEquals('a', $annot->foo[0]);
        self::assertInternalType('array', $annot->foo[1]);
        self::assertEquals('c', $annot->foo[2]);

        $array = $annot->foo[1];
        self::assertTrue(isset($array[0]));
        self::assertEquals('b', $array[0]);
    }

    public function testIssue67_2()
    {
        $parser = $this->createTestParser();

        // Nested arrays with nested annotations
        $result = $parser->parse('@Name("a", { "b" })');
        $annot = $result[0];

        self::assertInstanceOf(Name::class, $annot);
        self::assertNull($annot->value);
        self::assertCount(2, $annot->foo);
        self::assertEquals('a', $annot->foo[0]);
        self::assertInternalType('array', $annot->foo[1]);

        $array = $annot->foo[1];
        self::assertTrue(isset($array[0]));
        self::assertEquals('b', $array[0]);
    }

    public function testIssue67_3()
    {
        $parser = $this->createTestParser();

        // Nested arrays with nested annotations
        $result = $parser->parse('@Name("a", { "b" }, { "c" })');
        $annot = $result[0];

        self::assertInstanceOf(Name::class, $annot);
        self::assertNull($annot->value);
        self::assertCount(3, $annot->foo);
        self::assertEquals('a', $annot->foo[0]);
        self::assertInternalType('array', $annot->foo[1]);
        self::assertInternalType('array', $annot->foo[2]);

        $array1 = $annot->foo[1];
        self::assertTrue(isset($array1[0]));
        self::assertEquals('b', $array1[0]);

        $array2 = $annot->foo[2];
        self::assertTrue(isset($array2[0]));
        self::assertEquals('b', $array2[0]);
    }
```

**Comment by Ocramius** [comment] 2017-02-07 09:42
That looks good! Can you put them in a PR?

**Comment by sgehrig** [comment] 2017-02-07 10:13
@Ocramius No problem. Done.

**Comment by Ocramius** [comment] 2017-02-07 10:16
Awesome, closing here, let's continue in #119

**Closed by Ocramius** 2017-02-07 10:16 UTC
Labels: bug, missing tests
