### ISSUE TITLE
DocParser: bug parse property for multi-byte encodings

### ISSUE THREAD

**Issue by Defender32** [doctrine/annotations#262] opened 2019-03-27 10:55 UTC
selected language Turkey
Error:
Doctrine\Common\Annotations\DocParser->parse('/** @ODM\\Id */'
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Doctrine\ODM\MongoDB\Mapping\Annotations\I" in property ...

**Comment by Ocramius** [comment] 2019-03-27 13:39
@Defender32 please provide a failing test case in a new issue: closing here, since I can't reproduce this error.

I've just tested with this, and the annotation is correctly parsed (although it needs to be referenced correctly, so please check your CaSESensiTIVitY ;-) )

```php


    public function test262()
    {
        self::assertCount(1, $this->createTestParser()->parse('/** @odm\Id */'));
    }

    public function test262Uppercase()
    {
        self::assertCount(1, $this->createTestParser()->parse('/** @ODM\Id */'));
    }

    public function test262NoDocblockDelimiters()
    {
        self::assertCount(1, $this->createTestParser()->parse('@ODM\Id'));
    }

    public function test262NoNamespace()
    {
        self::assertCount(1, $this->createTestParser()->parse('@Id'));
    }
```

**Closed by Ocramius** 2019-03-27 13:39 UTC
